site_name: CICD Proxy
theme: 
  name: material
  logo: assets/ts-logo-white.png
  favicon: 'assets/favicon.ico'
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - meta
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
plugins:
  - render_swagger
